#!/bin/bash
# Author: Theodoros Pavlidis
# Backups Brave, Chrome & Firefox to "Data" hard disk.

# Brave backup.

rm -rf /run/media/pavlidis/Data/Backup/Browsers/Brave/* # Deletes previous Brave backup.
tar -jcvf brave.tar.bz2 .config/BraveSoftware/ # Backups and compresses Brave files.
mv brave.tar.bz2 /run/media/pavlidis/Data/Backup/Browsers/Brave/ # Moves Brave backup.

# Chrome backup.

# rm -rf /run/media/pavlidis/Data/Backup/Browsers/Chromium/* # Deletes previous Chrome backup.
# tar -jcvf chromium.tar.bz2 .config/chromium/ # Backups and compresses Chrome files.
# mv chromium.tar.bz2 /run/media/pavlidis/Data/Backup/Browsers/Chromium/ # Moves Chrome backup.

# Firefox backup.

rm -rf /run/media/pavlidis/Data/Backup/Browsers/Firefox/* # Deletes previous Firefox backup.
tar -jcvf firefox.tar.bz2 .mozilla # Backups and compresses Firefox files.
mv firefox.tar.bz2 /run/media/pavlidis/Data/Backup/Browsers/Firefox/ # Moves Firefox backup.
echo -e "\e[32mBrave & Firefox backup completed."
