#!/bin/bash
# Author: Theodoros Pavlidis
# Prints crypto prices using CoinGecko.

PRICES=$(curl -s https://www.coingecko.com/en | grep -i 'data-target="price.price"')

BTC=$(echo "$PRICES" | grep -i 'data-coin-symbol="btc"' | grep -oP '(?<=>).*' | tr -d '</span>')
ETH=$(echo "$PRICES" | grep -i 'data-coin-symbol="eth"' | grep -oP '(?<=>).*' | tr -d '</span>')
BNB=$(echo "$PRICES" | grep -i 'data-coin-symbol="bnb"' | grep -oP '(?<=>).*' | tr -d '</span>')
SOL=$(echo "$PRICES" | grep -i 'data-coin-symbol="sol"' | grep -oP '(?<=>).*' | tr -d '</span>')
ADA=$(echo "$PRICES" | grep -i 'data-coin-symbol="ada"' | grep -oP '(?<=>).*' | tr -d '</span>')
XRP=$(echo "$PRICES" | grep -i 'data-coin-symbol="xrp"' | grep -oP '(?<=>).*' | tr -d '</span>')
DOT=$(echo "$PRICES" | grep -i 'data-coin-symbol="dot"' | grep -oP '(?<=>).*' | tr -d '</span>')
LUN=$(echo "$PRICES" | grep -i 'data-coin-symbol="luna"' | grep -oP '(?<=>).*' | tr -d '</span>')
DOG=$(echo "$PRICES" | grep -i 'data-coin-symbol="doge"' | grep -oP '(?<=>).*' | tr -d '</span>')


echo "BTC = $BTC"
echo "ETH = $ETH"
echo "BNB = $BNB"
echo "SOL = $SOL"
echo "ADA = $ADA"
echo "XRP = $XRP"
echo "DOT = $DOT"
echo "LUN = $LUN"
echo "DOG = $DOG"
