#!/bin/bash
# Author: Theodoros Pavlidis
# Deletes "client.json" file of the Brave browser.

rm -rf ~/.config/BraveSoftware/Brave-Browser/Default/ads_service/client.json
echo -e "\e[32mBrave "client.json" deleted."
