#!/bin/bash
# Author: Theodoros Pavlidis
# Backups Encrypted USB Stick to "Data" hard Disk.

rm -rf /mnt/Data/Work/Βενζινάδικο/*
cd /run/media/pavlidis/016714d4-95cb-4244-89aa-84a65c3bf4bd/SmartManager
7z a -p -mx=1 -mhe -t7z -r SmartManager.7z Bash/ Hashes/ Wayland/ Xorg/ Zsh/
mv SmartManager.7z /mnt/Data/Work/Βενζινάδικο/
echo -e "\e[92mBackup is complete.\e[0m"
