#!/bin/bash
# Author: Theodoros Pavlidis
# Formats USB stick and encrypts it.

echo -e "\e[92m01. Unmount the USB stick and any external hard disks before running this Script.\e[0m"
echo -e "\e[92m01. Check with lsblk if the USB stick is indeed sdc1".\e[0m"
echo -e "\e[92m02. Once fdisk is running type 'd' to delete the existing partition.\e[0m"
echo -e "\e[92m03. Type 'n' to create a partition. Type 'p', hit enter three times, type 'Y' and type 'w'.\e[0m"
echo -e "\e[92m04. Type 'YES' and enter passphrase twice.\e[0m"
sudo fdisk /dev/sdc
sudo cryptsetup --type luks2 -c aes-xts-plain64 -h sha256 -s 256 -i 5000 luksFormat /dev/sdb1
sudo cryptsetup luksOpen /dev/sdc1 SmartManager
sudo mkfs.ext4 /dev/mapper/SmartManager
echo -e "\e[92mEncryption is completed. Please reboot and run 'sudo chown -R pavlidis /run/media/path_to_file/'\e[0m"
