#!/bin/bash
# Author: Theodoros Pavlidis
# Restores Encrypted USB Stick from "Data" hard Disk.

sudo rm -rf /run/media/pavlidis/cd /run/media/pavlidis/82d8029f-2e75-4f9d-9ce2-313ae0d70a87/SmartManager/*
sudo cp -r /mnt/Data/Work/Βενζινάδικο/SmartManager.7z /run/media/pavlidis/82d8029f-2e75-4f9d-9ce2-313ae0d70a87/SmartManager
cd /run/media/pavlidis/82d8029f-2e75-4f9d-9ce2-313ae0d70a87/SmartManager/
7za x SmartManager.7z
sudo rm /run/media/pavlidis/82d8029f-2e75-4f9d-9ce2-313ae0d70a87/SmartManager/SmartManager.7z
echo -e "\e[32mRestore is complete."
