#!/bin/bash
# Author: Theodoros Pavlidis
# Backups Browser files, Scripts, Virtual Machines and Wallpapers to "Data" hard disk.

BrowserBackup
ScriptsBackup
ConfigBackup
rsync -ah --delete ~/'VirtualBox VMs'/ /mnt/Data/'Virtual Machines'
echo -e "\e[92mVirtual Machines backup completed.\e[0m"
rsync -ah --delete --exclude={'.directory','.git','LICENSE','README.md'} ~/GitHub/Wallpapers/ /mnt/Data/Pictures/Wallpapers
echo -e "\e[92mWallpapers backup completed.\e[0m"
echo -e "\e[92mFull backup completed.\e[0m"
