#!/bin/bash
# Author: Theodoros Pavlidis
# Backups Browser files, Scripts and Wallpapers to "Data" hard disk.

BrowserBackup
ScriptsBackup
rsync -avh --delete --exclude={'.directory','.git','LICENSE','README.md'} /home/pavlidis/GitHub/Wallpapers/ /mnt/Data/Pictures/Wallpapers
echo -e "\e[32mFull backup completed."
