#!/bin/bash
# Author: Theodoros Pavlidis
# Calculates Ioanna's age.

d=`echo 29`
m=`echo 07`
y=`echo 1987`

yy=`date "+%Y"`
mm=`date "+%m"`
dd=`date "+%d"`

if [ $y -le $yy ]
then
yyy=`expr $yy - $y`
mmm=`expr $mm - $m`
ddd=`expr $dd - $d`

if [ $m -gt $mm ]
then
yyy=`expr $yyy - 1`
mmm=`expr $mmm + 12`
fi

if [ $d -gt $dd ]
then
ddd=`expr $d - $dd`
ddd=`expr 31 - $ddd`
else
ddd=`expr $dd - $d`
fi

fi

echo -e "\e[92mΗ Ιωάννα είναι $yyy χρονών, $mmm μηνών και $ddd ημερών.\e[0m"
