#!/bin/bash
# Author: Theodoros Pavlidis
# Makes all scripts inside the "Scripts" folder executable.

cd GitHub/Scripts/
chmod +x *
echo -e "\e[32mAll scripts inside the "Scripts" folder are executable."
