#!/bin/bash
# Author: Theodoros Pavlidis
# Makes all scripts inside the "Scripts" folder executable.

cd ~/GitHub/Scripts/
chmod +x *
echo -e "\e[92mAll scripts inside the "Scripts" folder are executable.\e[0m"
