#!/bin/bash
# Author: Theodoros Pavlidis
# Calculates Vasiliki's age.

d=`echo 02`
m=`echo 11`
y=`echo 2020`

yy=`date "+%Y"`
mm=`date "+%m"`
dd=`date "+%d"`

if [ $y -le $yy ]
then
yyy=`expr $yy - $y`
mmm=`expr $mm - $m`
ddd=`expr $dd - $d`

if [ $m -gt $mm ]
then
yyy=`expr $yyy - 1`
mmm=`expr $mmm + 12`
fi

if [ $d -gt $dd ]
then
ddd=`expr $d - $dd`
ddd=`expr 31 - $ddd`
else
ddd=`expr $dd - $d`
fi

fi

echo "Η Βασιλική είναι $yyy χρονών, $mmm μηνών και $ddd ημερών"
